### ISSUE TITLE
Document need ?

### ISSUE THREAD

**Issue by phongplus** [youaresoroman/react-ipfs#4]
this is awesome project , can you write some document for this ?
Also update npm to lastest version(0.3) with version 0.2 not working.

Thanks.

**Comment by youaresoroman** [comment]
Hello. For now, only is tsdoc compiled documentation is available. Planning to add storybook and basic implementation examples. 
Thank you for noticing. Version 0.3 update will be soon on npm

**Comment by phongplus** [comment]
Can be open pull request, i am very happy to join with document writing, also if using gitbook for document is awesome.
i am using this pack for my new project. 
Also can your explain true function to upload file.
```
const { ipfs } = useIPFS();
```

ipfs.original or ipfs.files ? or using ipfs.ls ?
Thanks so much.

**Comment by youaresoroman** [comment]
İn 0.3 useİPFS hook will return decorator class which only reason is to handle errors without stoping app while copying ipfs.js instance methods. You can use ipfs.original as you wish and the methods will be the same. 

`const { ipfs } = useİPFS()
//ipfs - is the İPFSDecorator class`

İn npm already exist 0.3.0-rc0 and the future versions will be inplemented on the base of it.

Take a look inside in examples folder to get info about how it will work in future versions.

İm sorry to inform but future versions will have a breaking changes

**Comment by phongplus** [comment]
that's great, and i'm on version 0.3.0-rc0. :) i using npm install with specific ^0.3.0-rc.0 and working great, thanks for this library because i skip building node server to handle ipfs. everything working in reactjs client. this library very useful, don't know why is less star in git :(

**Comment by youaresoroman** [comment]
Thanks! Looks like it because of almost empty documentation. İ hope to do it in the nearest future
