### ISSUE TITLE
Using another provider.

### ISSUE THREAD

**Issue by phongplus** [youaresoroman/react-ipfs#5]
For ipfs now is veryslow sometime i can not load. 
So this library can using another provider ?
Like : [infura](https://infura.io/), or [ipfsfile](https://nft.storage/) 

if  possible can let me how ?
Thanks you.

**Comment by youaresoroman** [comment]
Infura offers Node as Service, so in react-ipfs implementation, it's not possible.
Suggest to add in your node config multi addresses of other nodes in ipfs network for faster loading. [link for get info](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/BOOTSTRAP.md#ipfsbootstrapaddaddr-options)

`
const res = await ipfs.node.bootstrap.add(validIp4);
console.log(res.Peers);
`

**Comment by phongplus** [comment]
Sorry i can not using that implement. after i research i show some suggest is using https://www.pinata.cloud/ but i dont know how to implement with this library. 
Thanks you.

**Comment by youaresoroman** [comment]
Unfortunately, you can't connect with pinata directly. Pinata is the service not a public node. Only one thing i can suggest is to handle in you app file additions and then pinning it with Pinata. Please check their documentation
